### PR TITLE
Updated bot.py To also get corona virus data

### PR DESCRIPTION
**Pull request by PranavMurali**
Used Covidpy to get covid19 data in an embed directly to your discord server.
#1

### CODE REVIEW

**Comment by Attupatil** [comment]
Hello @PranavMurali 
Can you please provide Comment about how to use the Command
`sudo corona <?>`
And please check the indentation in  line 153

**Comment by PranavMurali** [comment]
Sure gimme a second I'll add it real quick

**Comment by PranavMurali** [comment]
I've updated the file with both the indentation and the comment on how to use the command.
Thanks!

**Comment by Attupatil** [comment]
Hello @PranavMurali 
But there is still some something missing
Screenshot_20201006-185422
Anyway thanks for the update
Marking it as hacktober fest accepted

**Comment by PranavMurali** [comment]
id like to fix it
gimme like 10 minutes, i wanna see it through

**Comment by Attupatil** [comment]
You made it..🎉🎉

**Pull request merged**
